export type FondyType = {
  order_id: string,
  merchant_id: string,
  order_desc: string,
  currency: string,
  amount: number,
  response_url: string,
  server_callback_url?: string,
  signature?: string
}

// Параметри фінальної відповіді Fondy
export type PaymentCallbackDataFondyType = {
  order_id: string,
  merchant_id: number
  amount: number,
  currency: string,
  order_status: string,
  response_status: string,
  signature: string,
  tran_type: string,
  sender_cell_phone: string,
  sender_account: string,
  masked_card: string,
  card_bin: number,
  card_type: string,
  rrn: string,
  approval_code: string,
  response_code: number,
  response_description: string,
  reversal_amount: number,
  settlement_amount: number,
  settlement_currency: string,
  order_time: string,
  settlement_date: string,
  eci: number,
  fee: number,
  payment_system: string,
  sender_email: string,
  payment_id: number,
  actual_amount: number,
  actual_currency: string,
  product_id: string,
  merchant_data: string,
  verification_status: string,
  rectoken: string,
  rectoken_lifetime: string,
  additional_info: JSON | string,
}